In [3]:
import numpy as np 


In [13]:
given_matrix = np.array([[1 , 2 ,3 ] , [4 ,5 ,6 ] , [7 , 8 ,9]])
maximum = np.max(given_matrix)
print(maximum)
minimum = np.min(given_matrix)
print(minimum)

9
1


In [25]:
#2 
#A Number of rows and column in the array
my_array = np.array([[ 3,5,8] , [6,7,9] , [9,12,3]])
my_array.shape

#B Sum of the values in the matrix
sum_of_matrix = np.sum(my_array)
print(sum_of_matrix)


62


In [37]:
#3 
#A
m1 = np.array([[2,8,10] , [3,5,1] , [7,12,0]])
m2 = np.array([[4,6,2] , [9,5,1] , [5,3,2]])
m_add = np.add(m1 , m2)
m_add


array([[ 6, 14, 12],
       [12, 10,  2],
       [12, 15,  2]])

In [35]:
m_sub = np.subtract( m1 ,m2)
m_sub

array([[-2,  2,  8],
       [-6,  0,  0],
       [ 2,  9, -2]])

In [41]:
m_mutiply = np.multiply(m1 , m2)
m_mutiply

array([[ 8, 48, 20],
       [27, 25,  1],
       [35, 36,  0]])

In [111]:
#4Count the frequency of unique values in Numpy array
#convert into list
my_array = ([ 4 ,5 ,6 ,10 ,5 , 10 , 45 ,54 ,12 , 45 , 23])
my_list = list(my_array)
print(my_list)
empty_dict = {}
for i in my_array:
    if i in empty_dict :
       empty_dict[i] += 1
    else :
       empty_dict[i] = 1
print(empty_dict)
        
print(my_list) 

[4, 5, 6, 10, 5, 10, 45, 54, 12, 45, 23]
{4: 1, 5: 2, 6: 1, 10: 2, 45: 2, 54: 1, 12: 1, 23: 1}
[4, 5, 6, 10, 5, 10, 45, 54, 12, 45, 23]


In [69]:
#negative into zeros
na = np.array([6,2,3,-4,2,-2,3])
no_negative = np.where(na < 0 , 0,na)  #np.where(condition , value_if_true , vvalue_if_false)
no_negative


array([6, 2, 3, 0, 2, 0, 3])

In [73]:
#5. Statistical operations
#!. Median
my_array = ([[20,30,40],[50,60,70],[20,10,80]])
my_median = np.median(my_array)
my_median

40.0

In [77]:
#2.Mean
my_mean = np.mean(my_array)
my_mean

42.22222222222222

In [85]:
my_variance = np.var(my_array)
my_variance

528.395061728395

In [87]:
standard_dev = np.std(my_array)
print(standard_dev)

22.98684540619689


In [36]:
#6
import numpy as np 
my_array = np.arange(100 , 200 , 10)
my_array.reshape(5,2)


array([[100, 110],
       [120, 130],
       [140, 150],
       [160, 170],
       [180, 190]])

In [40]:
#7. Return 
sample_array = np.array([[11,22,33] , [44,55,66],[77,88,99]])
sample_array[: ,2]

array([33, 66, 99])